version: '3.1'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: main
      MYSQL_USER: main
      MYSQL_PASSWORD: main
    ports:
      - "3306:3306"
    volumes:
      - "../docs/table-schema.sql:/docker-entrypoint-initdb.d/table-schema.sql"
