# 유저 테이블
CREATE TABLE USER (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(128) NOT NULL,
    PASSWORD_SALT VARCHAR(128) NOT NULL,
    STATUS ENUM('ADMIN', 'USER', 'WITHDRAW', 'SLEEP'),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

# 유저 인적사항/개인정보 테이블
CREATE TABLE USER_PERSONAL_INFO (
    USER_ID INT PRIMARY KEY,
    GENDER ENUM('MALE', 'FEMALE'),
    AGE INT,
    FOREIGN KEY (USER_ID) REFERENCES USER(ID) ON DELETE CASCADE
);

# 설문조사 (투표) 테이블
CREATE TABLE SURVEY (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    AUTHOR_ID INT NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    CONTENT TEXT,
    IS_DELETED BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (AUTHOR_ID) REFERENCES USER(ID)
);

# 설문조사 선택지 테이블
CREATE TABLE SURVEY_OPTION (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    SURVEY_ID INT NOT NULL,
    CONTENT TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (SURVEY_ID) REFERENCES SURVEY(ID) ON DELETE CASCADE
);

# 설문조사 답변 테이블 (투표 결과 집계용)
CREATE TABLE SURVEY_ANSWER (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    SURVEY_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    OPTION_ID INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SURVEY_ID) REFERENCES SURVEY(ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES USER_PERSONAL_INFO(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (OPTION_ID) REFERENCES SURVEY_OPTION(ID) ON DELETE CASCADE
);

# 해시태그 테이블
CREATE TABLE HASHTAGS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

# 설문조사 해시태그 테이블
CREATE TABLE SURVEY_HASHTAGS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    SURVEY_ID INT NOT NULL,
    HASHTAG_ID INT NOT NULL,
    FOREIGN KEY (SURVEY_ID) REFERENCES SURVEY(ID) ON DELETE CASCADE,
    FOREIGN KEY (HASHTAG_ID) REFERENCES HASHTAGS(ID) ON DELETE CASCADE
);

# 설문조사 좋아요 테이블
CREATE TABLE SURVEY_LIKE
(
    ID         INT PRIMARY KEY AUTO_INCREMENT,
    SURVEY_ID  INT NOT NULL,
    USER_ID    INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SURVEY_ID) REFERENCES SURVEY (ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES USER (ID) ON DELETE CASCADE
);

# 설문조사 댓글 테이블
CREATE TABLE SURVEY_COMMENT (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    SURVEY_ID INT NOT NULL,
    AUTHOR_ID INT NOT NULL,
    CONTENT TEXT,
    IS_DELETED BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SURVEY_ID) REFERENCES SURVEY(ID) ON DELETE CASCADE,
    FOREIGN KEY (AUTHOR_ID) REFERENCES USER(ID) ON DELETE CASCADE
);
